# Jupyter Notebooks

- Edit-Mode
    - Auto-Completion: irgendetwas tippen -> 'Tab' -> Auswahl and Completion-Möglichkeiten
    - Documentation: 'Shift+Tab' mit dem Cursor irgendwo in einer Funktion / Klasse (auch in den Klammern für die Argumente)
    - Zellen ausführen mit 'Cmd-Enter' / 'Ctrl-Enter' ||| 'Shift-Enter' -> ausführen + nächste Zelle
    - 'Esc', um in den Cell-Mode zu wechseln
- Cell-Mode (nicht offizielle Begriffe) mit 
    - Pfeiltasten zwischen den Zellen navigieren
    - 'a' (above) 'b' (below) neue Zellen erstellen
    - 'dd' Zellen löschen
    - 'm' (Markdown) und 'y' (Code) den Zell-Typ ändern
    - 'alt'/'option' gedrückt halten und mit der Maus über den Text ziehen: block-mark-mode (auch nicht-offizieller Begriff)
    - 'Enter', um in den Edit Mode der ausgewählten Zelle zu wechseln
- Jupyter Extensions
    - [enable extensions](https://tljh.jupyter.org/en/latest/howto/admin/enable-extensions.html)

# Markdown

# Title
## Heading 1
### Heading 2
...
###### Heading 6

Man kann hier einfach Text schreiben - mit ein paar extra-Zeichen, kann der Text formatiert werden, z.B.

- **Text in doppelten Sternchen ist fett**
- *Text in einfachen Sternchen ist kursiv*
- Stichpunkte mit 'Minus'
- `Backticks für Code in Markdown` (in deutscher Mac-Tastatur 'Shift' + eine Taste links neben 'Delete' für Backticks)

1. Nummerierte Stichpunkte mit Ziffern
2. Unterlisten mit Einrückung (Tab)
    - hier ist eine Unterliste
    - mit noch einem zweiten Punkt
3. Links:
    - [Angezeigter Link-Text](URL)

![Alternative Text](https://cdn11.bigcommerce.com/s-dwlxj/images/stencil/2560w/products/3146/5285/60watt-edison-bulb__02843.1508283240.jpg?c=2)

# Numpy

In [11]:
import numpy as np

## Numpy Arrays vs. Listen / Tuples

In [12]:
# numpy-arrays

# eigentlich gibt es in Python verschiedene Listen-Typen
[1, 2, 3] # Liste

[1, 2, 3]

In [13]:
(1, 2, 3) # Tuple

(1, 2, 3)

In [14]:
[[1, 2, 3], [4, 5, 6]] # ein Beispiel fuer eine verschachtelte Liste

[[1, 2, 3], [4, 5, 6]]

In [15]:
np.array([1, 2, 3]) # numpy-array (eigentlich wird hier aus einer Liste ein np-array erstellt)

array([1, 2, 3])

In [26]:
a_l = [1, 2, 3]
b_l = [4, 5, 6]

a_l + b_l # + Operation auf Listen
# concatenate

[1, 2, 3, 4, 5, 6]

In [17]:
a_np = np.array([1, 2, 3])
b_np = np.array([4, 5, 6])

a_np + b_np # + Operation auf np-arrays
# Operationen werden elementweise ausgefuehrt

array([5, 7, 9])

## datentypen in np-arrays vs in Listen

In [18]:
# listen sind sehr flexibel:
[1, "hallo", 1.4, [4, 5, 7]]

[1, 'hallo', 1.4, [4, 5, 7]]

In [20]:
np.array([1, "hallo", 1.4]) # hier wurden alle datentypen der elemente in strings ge-castet

array(['1', 'hallo', '1.4'], dtype='<U32')

In [21]:
np.array([1, 1.4]) # hier wurden alle datentypen der elemente in floats ge-castet

array([1. , 1.4])

In [24]:
np.array([1, 1.4], dtype=str) # type-casting selbst bestimmen mit dem argument 'dtype'

array([1, 1])

In [19]:
np.array([1, "hallo", 1.4, [4, 5, 7]])

/var/folders/z5/dpzrln312ds6fqzfbcyp_t9m0000gn/T/ipykernel_29940/3555730902.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([1, "hallo", 1.4, [4, 5, 7]])


array([1, 'hallo', 1.4, list([4, 5, 7])], dtype=object)

## Recheneffizienz mit Numpy-Arrays vs. Listen

In [51]:
# beispiel: elementweise addieren

# listen: 

added_list = []

for index in range(len(a_l)):
#     print(index)
    added_list.append(a_l[index] + b_l[index])

added_list

[5, 7, 9]

In [52]:
def add_lists(a_l, b_l):
    
    added_list = []
    
    for index in range(len(a_l)):
        added_list.append(a_l[index] + b_l[index])
    
    return added_list

In [58]:
# elementweise addieren mit sehr grossen listen

a_l = []
b_l = []

for i in range(10000000):
    a_l.append(i)
    b_l.append(i * 2)

In [62]:
%timeit add_lists(a_l, b_l)

675 ms ± 3.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [60]:
a_np = np.array(a_l)
b_np = np.array(b_l)

In [63]:
%timeit a_np + b_np

7.83 ms ± 248 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# --> elementweise verrechnen mit np-arrays ist viel schneller als mit Listen

In [ ]:
# in diese np-arrays werden wir vor allem audio-daten schreiben, verrechnen, etc.