# Numpy

In [1]:
import numpy as np

## Numpy Arrays vs. Listen / Tuples

In [2]:
# numpy-arrays

# eigentlich gibt es in Python verschiedene Listen-Typen
[1, 2, 3] # Liste

[1, 2, 3]

In [3]:
(1, 2, 3) # Tuple

(1, 2, 3)

In [4]:
[[1, 2, 3], [4, 5, 6]] # ein Beispiel fuer eine verschachtelte Liste

[[1, 2, 3], [4, 5, 6]]

In [5]:
np.array([1, 2, 3]) # numpy-array (eigentlich wird hier aus einer Liste ein np-array erstellt)

array([1, 2, 3])

In [6]:
a_l = [1, 2, 3]
b_l = [4, 5, 6]

a_l + b_l # + Operation auf Listen
# concatenate

[1, 2, 3, 4, 5, 6]

In [7]:
a_np = np.array([1, 2, 3])
b_np = np.array([4, 5, 6])

a_np + b_np # + Operation auf np-arrays
# Operationen werden elementweise ausgefuehrt

array([5, 7, 9])

## datentypen in np-arrays vs in Listen

In [8]:
# listen sind sehr flexibel:
[1, "hallo", 1.4, [4, 5, 7]]

[1, 'hallo', 1.4, [4, 5, 7]]

In [9]:
np.array([1, "hallo", 1.4]) # hier wurden alle datentypen der elemente in strings ge-castet

array(['1', 'hallo', '1.4'], dtype='<U32')

In [10]:
np.array([1, 1.4]) # hier wurden alle datentypen der elemente in floats ge-castet

array([1. , 1.4])

In [11]:
np.array([1, 1.4], dtype=str) # type-casting selbst bestimmen mit dem argument 'dtype'

array(['1', '1.4'], dtype='<U3')

In [12]:
np.array([1, "hallo", 1.4, [4, 5, 7]])

/var/folders/z5/dpzrln312ds6fqzfbcyp_t9m0000gn/T/ipykernel_28395/3555730902.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([1, "hallo", 1.4, [4, 5, 7]])


array([1, 'hallo', 1.4, list([4, 5, 7])], dtype=object)

## Recheneffizienz mit Numpy-Arrays vs. Listen

In [13]:
# beispiel: elementweise addieren

# listen: 

added_list = []

for index in range(len(a_l)):
#     print(index)
    added_list.append(a_l[index] + b_l[index])

added_list

[5, 7, 9]

In [14]:
def add_lists(a_l, b_l):
    
    added_list = []
    
    for index in range(len(a_l)):
        added_list.append(a_l[index] + b_l[index])
    
    return added_list

In [15]:
# elementweise addieren mit sehr grossen listen

a_l = []
b_l = []

for i in range(10000000):
    a_l.append(i)
    b_l.append(i * 2)

In [16]:
%timeit add_lists(a_l, b_l)

696 ms ± 8.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
a_np = np.array(a_l)
b_np = np.array(b_l)

In [18]:
%timeit a_np + b_np

8.42 ms ± 96.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
# --> elementweise verrechnen mit np-arrays ist viel schneller als mit Listen

In [20]:
# in diese np-arrays werden wir vor allem audio-daten schreiben, verrechnen, etc.

## Array Operationen

In [1]:
a = np.array([1, 3, 49, 81, 5, 67])

In [3]:
print(a + 1)
print(a * 2)
print(a / 2)
print(a < 6)

print(a + np.array([100, 200, 300, 400, 500, 600]))
# dimensionen und shape muessen gleich sein

[ 2  4 50 82  6 68]
[  2   6  98 162  10 134]
[ 0.5  1.5 24.5 40.5  2.5 33.5]
[ True  True False False  True False]
[101 203 349 481 505 667]


In [5]:
print(np.shape(a))
print(a.shape)

(6,)
(6,)


## Multidimensionale Arrays

In [6]:
b = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(b)
# wird wie eine tabelle oder (in diesem fall 2d-)matrix behandelt

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(b.shape)

(3, 3)


In [8]:
# 3d
# (4, 7, 8)

print(np.arange(10))
print(np.arange(2, 10))
print(np.arange(2, 10, 3))
      
      
np.reshape(np.arange(224), newshape=(4, 7, 8))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 5 8]


array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

## Auf Elemente zugreifen

### einzelne Elemente

In [9]:
print(a)

print(a[1])

print(a[-2]) # vor-vor-letztes element

print()

print(b, '\n')

print(b[1], '\n')

print(b[0][1], '\n')

print(b[0, 1], '\n')

[ 1  3 49 81  5 67]
3
5

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4 5 6] 

2 

2 



In [10]:
b_list = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]

print(b_list)
print(b_list[0][1])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2


In [11]:
b_list[0, 1] #funktioniert nicht bei listen

TypeError: list indices must be integers or slices, not tuple

### mehrere Elemente

In [12]:
print(a)
print(a[1:4]) # die rechte grenze ist exklusiv, d.h. wir haben eine element-range von 1-3 
print(a[1:])
print(a[:4])
print(a[:])
print(a[:-1]) # mit -1 die elemente von hinten zaehlen
print(a[:-2])

print()

# boolean index
print(np.array([True, False, False, True, False, True]))
print(a[ np.array([True, False, False, True, False, True]) ])
# auch hier muessen die dimensionen einander entsprechen

[ 1  3 49 81  5 67]
[ 3 49 81]
[ 3 49 81  5 67]
[ 1  3 49 81]
[ 1  3 49 81  5 67]
[ 1  3 49 81  5]
[ 1  3 49 81]

[ True False False  True False  True]
[ 1 81 67]


In [13]:
print(b, '\n')

print(b[1:3], '\n')

print(b[1:], '\n')
print(b[:2], '\n')
print(b[:-1], '\n')

print(b[0:2 , 1], '\n')

print(b[0:2 , 1:2], '\n')

print(b[0:2 , 1:3], '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]] 

[2 5] 

[[2]
 [5]] 

[[2 3]
 [5 6]] 



### bool-index

In [ ]:
# wie kann man auf 2 und 6 zugreifen

# sieve <-> Sieb

bool_idx = np.array([ [False, True,  False],
                      [False, False, True ],
                      [False, False, False]])

print(bool_idx)

print(b[bool_idx])



print()
# bool-index eleganter erstellen

# bool_idx = (b == 2) or (b == 6) # funktioniert so nicht
                                  # (aber nur wegen syntax - der gedanke an sich fuehrt zum Ziel)
    
bool_idx = np.logical_or(   b == 2,    b == 6   )

print(bool_idx)



print()
# for-schleife

j = 1
for i in range(2):
    if (j > 2):
        break
    print(b[i, j])
    j += 1
    
    

print()
# for-schleife

for i in range(2):
    print(b[i, i + 1])

# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

## Arrays erstellen

In [14]:
print(np.arange(50, 100, 4))

np.linspace # --> Shift-Tab fuer Documentation

print(np.linspace(50, 100, num=10)) # bei linspace ist das 'stop'-argument **nicht** exklusiv

print(np.linspace(50, 98, num=13))

print(np.linspace(50, 98, num=13, dtype=int))

print(np.zeros(10))

print(np.ones(10))

print(np.ones(10) * 400)

[50 54 58 62 66 70 74 78 82 86 90 94 98]
[ 50.          55.55555556  61.11111111  66.66666667  72.22222222
  77.77777778  83.33333333  88.88888889  94.44444444 100.        ]
[50. 54. 58. 62. 66. 70. 74. 78. 82. 86. 90. 94. 98.]
[50 54 58 62 66 70 74 78 82 86 90 94 98]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[400. 400. 400. 400. 400. 400. 400. 400. 400. 400.]


## datatypes

In [15]:
print(np.linspace(50, 98, num=13, dtype=int))
# datatypes koennen in fast jeder np-funktion mit dem 'dtype'-argument bestimmt werden

[50 54 58 62 66 70 74 78 82 86 90 94 98]


## Pi

In [16]:
np.pi

3.141592653589793

## Sine-Function

In [2]:
print(np.sin(0))
print(np.round(np.sin(1 / 4 * np.pi), 2))
print(np.round(np.sin(1 / 2 * np.pi), 2))
print(np.round(np.sin(3 / 4 * np.pi), 2))
print(np.round(np.sin(1 * np.pi), 2))
print(np.round(np.sin(5 / 4 * np.pi), 2))
print(np.round(np.sin(3 / 2 * np.pi), 2))
print(np.round(np.sin(7 / 4 * np.pi), 2))
print(np.round(np.sin(2 * np.pi), 2))

0.0
0.71
1.0
0.71
0.0
-0.71
-1.0
-0.71
-0.0


## Runden

In [1]:
print(np.round(2.4941813948519385293874934857, 0))
print(np.round(2.4941813948519385293874934857, 1))
print(np.round(2.4941813948519385293874934857, 3))

2.0
2.5
2.494
